OnlinePlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from User.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('user/', include('User.urls', namespace='user')),
    path('work/', include('Works.urls', namespace='work')),

]

User/urls.py
from django.urls import path

from User.views import login, register

app_name = 'user'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
]

Works/urls.py
from django.urls import path

app_name = 'work'

urlpatterns = [

]

User/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    nickname = models.CharField(max_length=64, null=True)
    phone = models.CharField(max_length=11)
    password = models.CharField(max_length=256)
    emial = models.EmailField(null=True)
    universities = models.CharField(max_length=64, null=True)
    introduction = models.TextField(null=True)

    def __str__(self):
        return self.nickname

    class Meta:
        db_table = 'user'

Works/models.py
from django.db import models

# Create your models here.

class Works(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    content = models.TextField(null=False)
    img = models.URLField(null=True)
    classification = models.CharField(max_length=64, null=True)
    label = models.CharField(max_length=64, null=True)
    user = models.ForeignKey('User.User', on_delete=models.CASCADE)

    class Meta:
        db_table = 'work'

class Comment(models.Model):
    id = models.AutoField(primary_key=True, unique=True) #unique唯一， 默认为False
    content = models.TextField()
    user = models.ForeignKey('User.User', on_delete=models.CASCADE)
    work = models.ForeignKey('Works', on_delete=models.CASCADE)


    class Meta:
        db_table = 'comment'

User/views.py
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render

# Create your views here.
from User.models import User



def index(request):
    return render(request, 'base.html')


def register(request):
    if request.method == 'GET':
        return '3'
    else:
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        re_password = request.POST.get('re_password')

        if password == re_password:
            makepassword = make_password(password) #自有加密方法
            user = User()
            user.phone = phone
            user.password = makepassword
            user.save()
            return '3'

def login(request):
    if request.method == 'GET':
        return render(request, 'User/login.html')
    else:
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        user = User.objects.filter(phone=phone)
        if user:
            if check_password(password, user.password):
                request.session['user'] = user
                return 'login seccess'
            else:
                return 'password is error'
        else:
            return 'user does not exist'


def logout(request):
    pass

Works/views.py
from django.shortcuts import render

# Create your views here.

templates/User/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <style>
        body{
            background-color: cadetblue;
        }
        #app_login{
            width: 500px;
            height: 600px;
            margin: auto;
            margin-top: 20px;
        }

    </style>
</head>
<body>
<div id="app_login">
    <form class="form-horizontal" action="{% url 'user:login' %}" method="post">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" placeholder="手机号">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> 记住我
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">登录</button>
            </div>
        </div>
    </form>
</div>

</body>
</html>

templates/User/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form class="form-horizontal">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Remember me
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Sign in</button>
            </div>
        </div>
    </form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <title>{% block title %}

    {% endblock %}</title>

        {% block mycss %}
            <style>
                #content{
                    width: 500px;
                    height: 300px;
                    margin: auto;
                }

            </style>
        {% endblock %}
</head>
<body>
<div id="nav">
    {% block nav %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Brand</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
                        {#                        <li><a href="#">Link</a></li>#}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">分类 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                    <!-- 插入判断用户是否登录功能-->
                    {% if request.session %}

                    {% endif %}
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    {% endblock %}
</div>
<div id="content">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>